trying to cache brew meta

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -47,14 +47,28 @@ _templates:
     os: osx
     language: generic
     osx_image: xcode12u
-    before_install:
-      # Travis has very low openfiles limit and fails often for OSX. Change that here.
-      - ulimit -n 1024;
-      # export PATH needs to be here and can't be inside before_install.sh
-      - mkdir -p $HOME/.bin
-      - export PATH=$PATH:$HOME/.bin
-      - .travis/before_install.sh
-      - export PATH="/usr/local/opt/python@3.7/bin:$PATH"
+    before_install: |
+        # Travis has very low openfiles limit and fails often for OSX. Change that here.
+        ulimit -n 1024
+        # export PATH needs to be here and can't be inside before_install.sh
+        mkdir -p $HOME/.bin
+        export PATH=$PATH:$HOME/.bin
+        .travis/before_install.sh
+        export PATH="/usr/local/opt/python@3.7/bin:$PATH"
+        export PATH="/usr/local/sbin:$PATH"
+             TAPS="$(brew --repository)/Library/Taps"
+             if [ -e "$TAPS/caskroom/homebrew-cask" -a -e "$TAPS/homebrew/homebrew-cask" ]; then
+                 rm -rf "$TAPS/caskroom/homebrew-cask"
+             fi
+             find "$TAPS" -type d -name .git -exec \
+                     bash -xec '
+                         cd $(dirname '\''{}'\'') || echo "status: $?"
+                         git clean -fxd || echo "status: $?"
+                         sleep 1 || echo "status: $?"
+                         git status || echo "status: $?"' \; || echo "status: $?"
+        fi
+        brew cleanup
+
     install:
       - pip3 install virtualenv
       - virtualenv -p python3 ~/venv
@@ -62,6 +76,17 @@ _templates:
       - .travis/install.sh
     script:
       - python pytestgeventwrapper.py $COVERAGE_ARGS rotkehlchen/
+    before_cache:
+      # When Taps is cached, this dir causes "Error: file exists" on `brew update`
+      if [ -e "$(brew --repository)/Library/Taps/homebrew/homebrew-cask/homebrew-cask" ]; then
+        rm -rf "$(brew --repository)/Library/Taps/homebrew/homebrew-cask/homebrew-cask"
+      fi
+    cache:
+      directories:
+        - ~/venv
+        - $HOME/Library/Caches/Homebrew
+        - $HOME/Library/Caches/pip
+        - /usr/local/Homebrew
 
   job-template-frontend: &job-template-frontend
     os: linux
@@ -70,20 +95,11 @@ _templates:
     before_install:
       - cd ./frontend/app
 
-before_cache:
-  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew cleanup; fi
-  # Credit https://discourse.brew.sh/t/best-practice-for-homebrew-on-travis-brew-update-is-5min-to-build-time/5215/9
-  # Cache only .git files under "/usr/local/Homebrew" so "brew update" does not take 5min every build
-  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then find /usr/local/Homebrew \! -regex ".+\.git.+" -delete; fi
 
 cache:
   pip: true
   npm: true
   directories:
-    - ~/venv
-    - $HOME/Library/Caches/Homebrew
-    - $HOME/Library/Caches/pip
-    - /usr/local/Homebrew
     - $HOME/.cache/pip
     - $HOME/.cache/.rotkehlchen-test-dir
     - $HOME/.ethash
